# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='data',
            field=models.CharField(max_length=255),
        ),
    ]
