# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0002_auto_20171028_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hash',
            name='data',
            field=models.TextField(),
        ),
    ]
