# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0003_auto_20171028_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hash',
            name='user',
        ),
        migrations.DeleteModel(
            name='Hash',
        ),
        migrations.DeleteModel(
            name='User_conf',
        ),
    ]
